# Generated by Django 5.1.3 on 2025-04-11 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ap', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='groupId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ap.group'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='subjectId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ap.subject'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='teacherId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ap.teacher'),
        ),
    ]
