# Generated by Django 5.1.3 on 2025-05-06 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ap', '0002_alter_schedule_groupid_alter_schedule_subjectid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='day',
            field=models.DateField(),
        ),
    ]
