version: '3.8'

networks:
  network:
   driver: bridge

services:

  app:
    environment:
      - DJANGO_SETTINGS_MODULE=server.settings
      - DEBUG=1 
    volumes:
      - ./server:/app/server
      - static_volume:/app/static
      - media_volume:/app/media
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - '8000:8000'
    networks:
      - network

    nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/static
      - media_volume:/app/media
    depends_on:
      - app
      
volumes:
  static_volume:
  media_volume: