version: '3.8'

networks:
  network:
   driver: bridge

services:

  app:
    environment:
      - DJANGO_SETTINGS_MODULE=server.settings
      - DEBUG=1 
    volumes:
      - ./server:/app/server
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - '8000:8000'
    networks:
      - network