version: '3.8'

services:
  app:
    build: .
    environment:
      - DJANGO_SETTINGS_MODULE=server.settings
    volumes:
      - ./server:/app/server
      - ./staticfiles:/app/server/staticfiles  # Единая точка монтирования
    command: daphne -b 0.0.0.0 -p 8000 server.asgi:application
    networks:
      - app_network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./staticfiles:/app/server/staticfiles:ro  # Только чтение
    depends_on:
      - app
    networks:
      - app_network

networks:
  app_network:
    driver: bridge